### ISSUE TITLE
Error when git cloning repo

### ISSUE THREAD

**Issue by aktarali** [hashicorp/terraform-google-nomad#3] opened 2017-11-22 10:24 UTC
Hi;

I git cloned this repo and received this error messages, please advise.

```
Alis-MacBook-Air:terraform-google-nomad aaktar$ terraform get
Get: git::ssh://git@github.com/hashicorp/terraform-google-consul.git?ref=v0.0.1
Error loading modules: error downloading 'ssh://git@github.com/hashicorp/terraform-google-consul.git?ref=v0.0.1': /usr/bin/git exited with 128: Cloning into '.terraform/modules/1216a0b2f43677d000c147c002a85f0c'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by josh-padnick** [comment] 2017-11-26 19:18
I'm afraid I can't reproduce this. Here's what I receive:

```
josh@pad-mac /p/tmp> git clone https://github.com/hashicorp/terraform-google-nomad
Cloning into 'terraform-google-nomad'...
remote: Counting objects: 137, done.
remote: Total 137 (delta 0), reused 0 (delta 0), pack-reused 137
Receiving objects: 100% (137/137), 1.34 MiB | 511.00 KiB/s, done.
Resolving deltas: 100% (63/63), done.
josh@pad-mac /p/tmp> cd terraform-google-nomad/
josh@pad-mac /p/t/terraform-google-nomad (master)> terraform get
Get: git::ssh://git@github.com/hashicorp/terraform-google-consul.git?ref=v0.0.1
Get: file:///private/tmp/terraform-google-nomad/modules/nomad-firewall-rules
Get: file:///private/tmp/terraform-google-nomad/modules/nomad-cluster
Get: file:///private/tmp/terraform-google-nomad/modules/nomad-firewall-rules
josh@pad-mac /p/t/terraform-google-nomad (master)>
```

This is definitely a public repo (hence your ability to submit this ticket!), so I'm assuming this is a local environment issue for you. The GitHub doc on [Error: Permission denied (publickey)](https://help.github.com/articles/error-permission-denied-publickey/) may help you resolve this.

I'm going to close this ticket since this issue is unrelated to this repo.

**Closed as completed by josh-padnick** 2017-11-26 19:18 UTC
